[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
framework = { path = "../crates/framework" }
infra = { path = "../crates/infra" }
rocket = "0.5.1"
dotenv = "0.15.0"
lambda_http = "0.14.0"
