[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.12.1", features = ["v4"] }
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.138"
async-trait = "0.1.86"
domain = { path = "../domain" }
