[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.217"
serde_json = "1.0.138"
infra = { path = "../infra" }
app = { path = "../app" }
